import Content from "@/components/Content";
import "../styles/globals.css";
import Header from "@/components/Header";
import { Analytics } from "@vercel/analytics/react";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#17181C] max-w-[1200px] mx-auto">
        <Header />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
